---
title: "04-report-template-oyo"
params:
  state: "Texas"
echo: true
---

## Set up

```{r}
#| label: setup
#| mesage: false
#| warning: false

library(tidyverse)
library(janitor)
```

### Import your files

```{r}
#| label: import

#copy from analysis
power_cleaned_list <- list.files(
  "data-processed-power",
  full.names = T
)

power_cleaned_list
```

### Combine all your files

```{r}
#| label: combine

#copy from analysis
all_outages <- map(
  power_cleaned_list,
  read_csv,
  col_type = cols(fips = col_character())
) |>
  list_rbind() |>
  clean_names()

all_outages
```

## OYO: 

### Create parameter list and filter for parameters

```{r}
#state_list <- 
```

States: (check your work)

```{r}
#outages <- all_outages |>

#outages
```

### Do some analysis for your state

- What is the most common cause of power outages?
- What cause leads to the longest power outages?

tip: use event_category instead of event_type

#### Common causes of outages
 
```{r}
#outages |>
```

#### Cause of longest outages

```{r}
#outages |>
```

