---
title: "Importing and function solutions"
format: html
---

## Set up

Importing our needed libraries. We use tidyverse for almost everything.

```{r}

#| label: setup   #<1>
#| message: false #<2>
#| warning: false #<3>

library(tidyverse)
library(janitor)
library(scales)

```

# Importing multiple files at once

```{r}
#| label: import-oyo

power_files_list <- list.files(
  "data-processed-power",
  full.names = T
)

power_files_list

```

```{r}
#| label: combine-files-oyo

power_all <- map(
  power_files_list,
  read_csv
) |>
  list_rbind() |>
  clean_names()

power_all |> glimpse()
```

```{r}
#| label: function

filter_graph_function <- function (state) {
  filtered_data <- power_all |> filter(state_event |> str_detect(state)) |>
    group_by (event_category) |> 
    summarize(total_events = n()) |> 
    arrange(total_events |> desc()) |> 
    head(10)
  
  ggplot(filtered_data, 
         aes(x = total_events, 
             y = reorder(event_category, total_events))) +
         geom_col() +
         labs(x = "Occurances", y = "Outage Cause")  +
        scale_x_continuous(labels = comma)
        
}

```


```{r}
filter_graph_function("Texas")
```




