---
title: "Taycleaning"
---

## Goals of this notebook

We will set up our data following these steps:

- Download and import our data
- Clean up data types and columns
- Export data by album/playlist

## Set up

```{r}

#| label: setup
#| message: false
#| warning: false

library(tidyverse)
library(janitor)

```

## Importing

Let's import our data into our notebook.

```{r}

#| label: import

taylor <- read.csv("data-raw-taylor/taylor_swift_spotify.csv") |> clean_names()

taylor |> glimpse()
```

## Remove unneeded columns

```{r}

#| label: remove

taylor_remove <- taylor |>
  select(-x, -id)

taylor_remove

```

## Fixing song length

```{r}

#| label: song-length

taylor_clean <- taylor_remove |> mutate(
  duration_min = duration_ms/60000
) |>
  select(-duration_ms)

taylor_clean

```

## Dividing by album

```{r}

#| label: export

taylor_split <- split(taylor_clean, taylor_clean$album)

folder_path <- "data-processed-taylor"

for(album in names(taylor_split)){
  file_name <- paste0(
    album |> str_replace(":", "-"), ".csv")
  file_path <- file.path(folder_path, file_name)
  write.csv(taylor_split[[album]], file_path, row.names =FALSE)
  
}
```

```{r}
taylor_clean |> write_rds("data-processed-taylor/taylor_disco.rds")
```

